// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kscinoowimgmqgsxleck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzY2lub293aW1nbXFnc3hsZWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjQxMzMsImV4cCI6MjA2ODg0MDEzM30.LaNbKFDaFaHglTfVi5-q9pC04mpbE1pPmGao6W6Rs9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});